#Archives - open/read/write
my_file = open('text.txt', 'w')
my_file.write('banana\n')
my_file.write('Eat 2 bananas')
my_file.close()
my_file = open('text.txt', 'r')
print(my_file.name)
contents = my_file.read()
print(contents)
my_file.close()
